import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// Generates a simple text-based receipt document (no heavy PDF lib required)
// For production, swap with @react-pdf/renderer or puppeteer
export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const receipt = await prisma.receipt.findFirst({
    where: { receiptId: params.id },
  });

  if (!receipt) {
    return NextResponse.json({ error: "Receipt not found" }, { status: 404 });
  }

  const explorerBase = "https://sepolia.arbiscan.io";
  const amount = (Number(receipt.amount) / 1e6).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
  });

  // Generate a clean HTML receipt that can be printed to PDF
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Receipt ${receipt.receiptId.slice(0, 12)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 48px; color: #0B1020; max-width: 640px; margin: 0 auto; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; padding-bottom: 24px; border-bottom: 2px solid #6D28D9; }
    .logo { font-size: 24px; font-weight: 700; color: #6D28D9; }
    .logo span { color: #2EE59D; }
    .receipt-label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 1px; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 10px; color: #999; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; }
    .field { margin-bottom: 12px; }
    .field-label { font-size: 11px; color: #666; margin-bottom: 2px; }
    .field-value { font-size: 14px; font-weight: 500; }
    .field-value.mono { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 11px; word-break: break-all; }
    .amount { font-size: 32px; font-weight: 700; color: #0B1020; margin: 16px 0; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
    .divider { border-top: 1px solid #E6ECF5; margin: 24px 0; }
    .footer { margin-top: 40px; padding-top: 24px; border-top: 1px solid #E6ECF5; font-size: 10px; color: #999; text-align: center; }
    .verification { background: #F7FAFF; border: 1px solid #E6ECF5; border-radius: 8px; padding: 16px; margin-top: 24px; }
    .verification a { color: #6D28D9; text-decoration: none; }
    @media print { body { padding: 24px; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">Arb<span>CFO</span></div>
      <div style="font-size:12px;color:#666;margin-top:4px;">Payment Receipt</div>
    </div>
    <div style="text-align:right;">
      <div class="receipt-label">Receipt</div>
      <div style="font-size:11px;font-family:monospace;margin-top:4px;">${receipt.receiptId.slice(0, 16)}…</div>
    </div>
  </div>

  <div class="amount">${amount} <span style="font-size:14px;color:#666;font-weight:400;">USDC</span></div>

  <div class="grid">
    <div class="field">
      <div class="field-label">Vendor</div>
      <div class="field-value">${receipt.vendorName || "—"}</div>
    </div>
    <div class="field">
      <div class="field-label">Date</div>
      <div class="field-value">${new Date(receipt.executedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</div>
    </div>
  </div>

  <div class="divider"></div>

  <div class="section">
    <div class="section-title">Onchain Details</div>
    <div class="field">
      <div class="field-label">Vendor Address</div>
      <div class="field-value mono">${receipt.vendor}</div>
    </div>
    <div class="field">
      <div class="field-label">Token</div>
      <div class="field-value mono">${receipt.token}</div>
    </div>
    <div class="field">
      <div class="field-label">Invoice Hash</div>
      <div class="field-value mono">${receipt.invoiceHash}</div>
    </div>
    <div class="field">
      <div class="field-label">Receipt ID (deterministic)</div>
      <div class="field-value mono">${receipt.receiptId}</div>
    </div>
    ${receipt.memoHash ? `<div class="field"><div class="field-label">Memo Hash</div><div class="field-value mono">${receipt.memoHash}</div></div>` : ""}
  </div>

  <div class="verification">
    <div class="section-title" style="margin-bottom:8px;">Verification</div>
    <p style="font-size:12px;margin-bottom:8px;">This receipt is immutably stored onchain on Arbitrum. Verify the transaction:</p>
    ${receipt.txHash ? `<a href="${explorerBase}/tx/${receipt.txHash}" style="font-size:11px;font-family:monospace;word-break:break-all;">${explorerBase}/tx/${receipt.txHash}</a>` : '<span style="font-size:11px;color:#999;">Transaction hash pending</span>'}
  </div>

  <div class="footer">
    Generated by ArbCFO · Audit-ready receipts on Arbitrum · ${new Date().toISOString()}
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="receipt-${receipt.receiptId.slice(0, 10)}.html"`,
    },
  });
}
